dataset: cifar10
model: convnet
method: idc
metric: mse
match: grad
data_dir: ./data
imagenet_dir: ./data/imagenet
save_dir: ./result
save_ckpt: false
data_pt: ''
augment: false
pretrained: false
plotter: true
load_memory: false
dsa: true
dsa_strategy: color_crop_flip_scale_rotate
aug_type: color_crop_cutout
num_workers: 8
batch_size: 64
batch_syn_max: 128
ipc: 1
repeat: 1
epochs: 300
init: mix
decode_type: single
factor: 2
mixup: cut
mixup_net: cut
mix_p: 0.5
beta: 1.0
seed: 0
device_ids: '0,1,2,3'
nclass: 10
num_classes: 10
size: 32
channel: 3
evaluation_model: [ 'convnet','resnet10_in','densenet' ]
model_params:
  densenet:
    nclass: 10
learning:
  loss: 'ce'
  optim: 'sgd'
  scheduler: 'multisteplr'
  sgd:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
niter: 2000
inner_loop: 100
n_data: 2000
lr_img: 0.005
mom_img: 0.5